spring.application.name=developpement_back_end

spring.datasource.url=jdbc:mysql://localhost:3306/projet-plateforme-cours
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


jwt.secret=monSecretJWTTresLongPourEtreSecurise123456789
jwt.expiration=86400000